### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by mikmeh** [santiagobasulto/slack-cli#4]
New to python and slack, bear with me please. 
Python 3.7.2 on Windows 10. PIP updated. Installed slack.py fine. 
When I tried to run the test to auth it failed. 

>>> slack -a xoxp-************* auth_test
  File "<stdin>", line 1
    slack -a xoxp-************* auth_test
                ^
SyntaxError: invalid syntax

redacted token for obvious reasons. 

I also tried as a string variable with the same results. 

>>> atoken = "xoxp-************"
>>> slack -a atoken auth_test
  File "<stdin>", line 1
    slack -a atoken auth_test
                  ^
SyntaxError: invalid syntax

**Comment by santiagobasulto** [comment]
Project will be archived.
